### ISSUE TITLE
Job lost and compute node not removed from SGE

### ISSUE THREAD

**Issue by apalazzin** [awslabs/cfncluster#148] opened 2016-11-03 15:46 UTC
Hi,
it happened several times that a job was launched inside a compute node during node termination and the job was lost at the end.

It seems a problem already known and already reported: https://github.com/awslabs/cfncluster/issues/56 https://github.com/awslabs/cfncluster/issues/67 https://forums.aws.amazon.com/thread.jspa?messageID=748891

After that, I noticed a node was still in SGE's registry (I can see it by `qhost`) while it was in "terminated" status in aws console.

`$ qstat -f`
```
queuename                      qtype resv/used/tot. load_avg arch          states
---------------------------------------------------------------------------------
all.q@ip-172-31-46-49.eu-west- BIP   0/0/1          -NA-     lx-amd64      auo

```

`$ qstat -explain acAE`
```
queuename                      qtype resv/used/tot. load_avg arch          states
---------------------------------------------------------------------------------
all.q@ip-172-31-46-49.eu-west- BIP   0/0/1          -NA-     lx-amd64      auo
	error: no value for "np_load_avg" because execd is in unknown state
```

In **sqswatcher log**, node is supposed to be removed from SGE, but failed. It said Host object "ip-172-31-46-49" is still referenced in cluster queue "all.q". But just before that, purging the node from "all.q" was just be done as shown in following snippet. You can find src code `/usr/local/lib/python2.7/site-packages/sqswatcher/plugins/sge.py L108`. 

I attached **sqswatcher log** and **sge log**. Anyone can help? @dougalb 

[sqswatcher.txt](https://github.com/awslabs/cfncluster/files/569402/sqswatcher.txt)
[messages.txt](https://github.com/awslabs/cfncluster/files/569401/messages.txt)

**Comment by kdyb** [comment] 2016-12-18 10:39
I have the same problem

**Comment by apalazzin** [comment] 2016-12-22 09:31
Hi,

I thought of a possible solution: disable the node from the cluster before you begin to free the resource (ie this command `sudo -u sgeadmin -i -d qmod all.q@ip-XXXXX.compute.internal`).

**Comment by andreas-wilm** [comment] 2017-01-31 13:40
Same problem here. Shouldn't disabling the node be handled automatically?

**Comment by xzy3** [comment] 2017-02-10 00:57
I had this happen to me too, though with a different cause. I had NFS problems which caused an uninterruptible sleep state on the job which never made progress. I eventually manually deleted the job directory from the /opt/sge spool. That fixed things and the node could be deleted from SGE. There may need to be a more aggressive way of detecting and cleaning up these wedged jobs when a node is being removed.

**Comment by xzy3** [comment] 2017-02-17 14:45
I just saw the problem without the NFS root cause. The lockHost code in the nodewatcher still has a race condition with SGE. Adding a exclusive complex resource, and then using `qsub -now y -hard -l exclusive=true -q all.q@hostname -b y qmod -d all.q@hostname` would be a more robust solution. That way the scheduler is in charge of making sure no jobs are scheduled when the node is disabled.

That would mean that the compute nodes would need to be administration nodes. This may already be the case I haven't checked.

@dougalb

**Comment by xzy3** [comment] 2017-02-17 16:25
Actually it looks like https://github.com/awslabs/cfncluster-node/blob/4f5b152d02a7d8ac82379221f1310ee50d30f4dc/sqswatcher/plugins/sge.py#L98-L100 may be the problem. The node has to be an admin host for `qmod -d` to work.

**Comment by tomazberisa** [comment] 2017-05-30 22:04
We are experiencing a similar issue: jobs that were in 't' mode (transferring to SGE execution host) when the spot instance is taken offline remain stuck in 't' mode. They never end up in an error mode and are therefore never restarted on a different execution host.

This seems to be the same behavior reported in #56

**Comment by xzy3** [comment] 2017-05-31 02:27
I've run traditional SGE clusters for a while. It's unlikely that your t-state problem is directly caused by this exact issue. The amount of time a job spends in t-state is normally very short. However, I see jobs get stuck in t pretty often on physical clusters. Normally you fix it by restarting sgeshepard on the compute node. It's more likely that your t-state is caused by something else, but when the scale-down hits things just get even more messed up.

**Closed** 2017-06-01 14:38 UTC

**Comment by cz2009111109** [comment] 2019-08-20 01:49
you must  delete the jobs of the snode ,wo delete and restart ,then it is ok
