### ISSUE TITLE
cfncluster returns an error when I use spot instances for compute fleet

### ISSUE THREAD

**Issue by 91bsjun** [awslabs/cfncluster#198] opened 2017-07-05 04:00 UTC
Here is my config template.
```
[aws]
aws_region_name = us-east-2

[cluster default]
vpc_settings = public
key_name = *********
compute_instance_type = c4.8xlarge
master_instance_type = m4.xlarge
initial_queue_size = 2
max_queue_size = 10
maintain_initial_size = false
cluster_type = spot
spot_price = 1.60
master_root_volume_size = 20
base_os = centos7
ebs_settings = custom

[vpc public]
master_subnet_id = subnet-*******
vpc_id = vpc-*********

[ebs custom]
volume_type = io1
volume_iops = 2000
volume_size = 2000
encrypted = true

[global]
update_check = true
sanity_check = true
cluster_template = default
```

And the occurred error in CloudForamtion
```
23:54:01 UTC+0900	DELETE_IN_PROGRESS	AWS::EC2::EIPAssociation	AssociateEIP	
23:53:56 UTC+0900	ROLLBACK_IN_PROGRESS	AWS::CloudFormation::Stack	cfncluster-test3	The following resource(s) failed to create: [ComputeFleet]. . Rollback requested by user.
23:53:55 UTC+0900	CREATE_FAILED	AWS::AutoScaling::AutoScalingGroup	ComputeFleet	Received 0 SUCCESS signal(s) out of 2. Unable to satisfy 100% MinSuccessfulInstancesPercent requirement
23:53:54 UTC+0900	UPDATE_IN_PROGRESS	AWS::AutoScaling::AutoScalingGroup	ComputeFleet	Failed to receive 2 resource signal(s) for the current batch. Each resource signal timeout is counted as a FAILURE.
23:23:53 UTC+0900	CREATE_IN_PROGRESS	AWS::AutoScaling::AutoScalingGroup	ComputeFleet	Resource creation Initiated
```

Are there some mistakes what I missing?

**Comment by bwbarrett** [comment] 2017-07-05 21:14
@91bsjun, you have an initial queue size of 2, so CfnCluster will try to create an autoscaling group with a desired instance count of 2.  Something in bringing up those two instances failed.  Some sleuthing is generally needed to find the root cause of the failure; there should be some errors in the autoscaling history to help.  You may have to use the `--norollback` option to CfnCluster to prevent CloudFormation from rolling back all the changes (and, therefore deleting all the history).  Debugging why clients don't start is sometimes easier if you specify `initial_queue_size = 0`, let the cluster build successfully, and then modify the AutoScaling group created by CfnCluster to have a desired size of 1 or 2 and track what is failing.

**Comment by 91bsjun** [comment] 2017-07-06 02:42
Thanks @bwbarrett . This problem probably due to the "Max spot instance limitation". Because when I try to make spot instance 'c4.8xlarge', AWS returns "Max spot instance count exceeded." Whereas, one 'm4.xlarge' was created successfully. So, when I run the cfncluster with 'm4.xlarge' as compute nodes, it created one compute node but the other one was failed. It seems that the number of spot instance limitation is 0 for 'c4.8xlarge' and 1 for 'm4.xlarge'. So I request to increase the maximum limitations.

**Comment by bwbarrett** [comment] 2017-07-06 15:10
Glad we could get you pointed in the right direction.  I'm going to close this issue; if you run into more problems, please open a new issue.

**Closed by bwbarrett** 2017-07-06 15:10 UTC
Labels: help wanted
